export const GET_DASHBOARD_DATA_REQUEST = 'GET_DASHBOARD_DATA_REQUEST';
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS';
export const GET_DASHBOARD_DATA_FAIL = 'GET_DASHBOARD_DATA_FAIL';

export const GET_DEMO_AUTH_DATA_REQUEST = 'GET_DEMO_AUTH_DATA_REQUEST';
export const GET_DEMO_AUTH_DATA_SUCCESS = 'GET_DEMO_AUTH_DATA_SUCCESS';
export const GET_DEMO_AUTH_DATA_FAIL = 'GET_DEMO_AUTH_DATA_FAIL';
