export const GET_AUDIENCE_DATA_REQUEST = 'GET_AUDIENCE_DATA_REQUEST';
export const GET_AUDIENCE_DATA_SUCCESS = 'GET_AUDIENCE_DATA_SUCCESS';
export const GET_AUDIENCE_DATA_FAIL = 'GET_AUDIENCE_DATA_FAIL';

export const GET_DEMO_AUTH_DATA_REQUEST = 'GET_DEMO_AUTH_DATA_REQUEST';
export const GET_DEMO_AUTH_DATA_SUCCESS = 'GET_DEMO_AUTH_DATA_SUCCESS';
export const GET_DEMO_AUTH_DATA_FAIL = 'GET_DEMO_AUTH_DATA_FAIL';
